%YAML:1.0

#camera calibration 
model_type: PINHOLE

#image resize factor. Note that, this factor MUST be same as OKVIS config file
resizeFactor: 0.5

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

fast_relocalization: 1

#loop closure 
#if you want to use loop closure to minimize the drift, set loop_closure true and give your brief pattern file path and vocabulary file path accordingly;
#also give the camera calibration file same as feature_tracker node
loop_closure_params:
    enable: 1  
    min_correspondences: 35
    pnp_reprojection_threshold: 12.0
    pnp_ransac_iterations: 100 

health:
    enable: 0
    min_keypoints: 15
    consecutive_keyframes: 3
    keyframe_wait_time: 2.0
    kps_per_quadrant: 1

debug_image: 1

image_height: 1100
image_width: 1600
distortion_coefficients: [0.1462139249855356, 0.3775304191882089, 0.007835564538475424, 0.002760598455182088]
focal_length: [1159.2905564436558, 1157.0215864700963]
principal_point: [804.4293114224579, 561.884540048856]
landmark_quality: 0.01