%YAML:1.0

#camera calibration 
model_type: PINHOLE
camera_name: slave1

#image resize factor. Note that, this factor MUST be same as OKVIS config file
resizeFactor: 0.5

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

fast_relocalization: 1

#loop closure 
#if you want to use loop closure to minimize the drift, set loop_closure true and give your brief pattern file path and vocabulary file path accordingly;
#also give the camera calibration file same as feature_tracker node
loop_closure_params:
    enable: 1  
    min_correspondences: 35
    pnp_reprojection_threshold: 8.0     

health:
    enable: 0
    min_keypoints: 15
    consecutive_keyframes: 3
    keyframe_wait_time: 2.0
    kps_per_quadrant: 1

debug_image: 0

image_height: 1200
image_width: 1600
focal_length: [1156.5188534683703, 1156.5772666173266]
principal_point: [763.2083316463371, 617.2779853849335]
distortion_coefficients: [-0.17473019446863114, 0.10643290428040156, 0.005210777878907861, -0.00028664918860079295]